### ISSUE TITLE
Add Detector Location Info to Title of Solar Analemma Plot; Fix download plot

### ISSUE THREAD

**Issue by stdye** [geoneutrinos/reactors#217]
The same info and format as on the main plot title is good.

The "download plot as a png" returns an empty Solar Analemma plot using Safari on my MacBook Air

**Comment by stdye** [comment]
Fix same download issue with the 8B Decay ES Rate Spectrum plot

**Comment by stdye** [comment]
Maybe download was intentionally disabled because solar neutrinos are not yet incorporated in the model? If so, ignore the "Fix download plot" portion of this issue.

**Comment by DocOtak** [comment]
Looks like this is a bug in plotly and was fixed 6 days ago https://github.com/plotly/plotly.js/issues/1227 it also looks like they did a release 3 days ago, so I think we just need to update plotly for the download fix.

**Comment by stdye** [comment]
This change doesn't show yet on the live site even after clearing my Safari browser history

Downloaded plot.png still shows empty, at east on Preview. Haven't tried another viewer.

**Comment by DocOtak** [comment]
Deploy failed... hold on

**Comment by stdye** [comment]
Uh oh, old plot tile commented out?

**Comment by stdye** [comment]
Detector location now appears on plot as well as the download. The reactor dots and the analemma curves still do not show on the downloaded plot

**Comment by DocOtak** [comment]
I guess it's still broken in Safari :(... what happens when you try to download the plot a second time?

**Comment by stdye** [comment]
Yes, on second download it all comes through!

**Comment by DocOtak** [comment]
There are a bunch of download options we can do: https://plotly.com/javascript/configuration-options/#customize-download-plot-options

I seem to recall Morgan asking for svg outputs, and we should probably make the file names nicer (like the download data filenames)

**Comment by stdye** [comment]
Indeed, output file names are totally generic now.

**Comment by stdye** [comment]
I will start a new (low priority) issue to address this

**Comment by rlreamy** [comment]
Has there been any movement on this? I am using the library and have an outstanding issue in one of my applications because of this. The only workarounds I know of are 1) export it a second time, and 2) export it as an svg instead of any of the other data types.
